### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by Jusdev89** [themeteorchef/adding-a-beta-invitation-system-to-your-meteor-application#4]
Hey im using this project as a starting point, but a can't get it to work on my modulus server. Its keeps giving me an error message about a ROOT_URL not specified. Do you have any clue what that means? Thanks you have a good one. ohh and im using the command 'modulus deploy'

**Comment by themeteorchef** [comment]
I do! In the Modulus dashboard, they have an admin section for your deployment. A ways down that page there's a table of environment variables. You want to add a variable with the name ROOT_URL with a value of either the Modulus domain name (displayed at the top of the admin page as Your Project URL), or, the sub domain you set. Make sure to use the full URL (http://...). Save this and restart your server and it should quit barking :)

**Comment by Jusdev89** [comment]
Wow thanks alot that was it.

**Comment by themeteorchef** [comment]
Cool! Good to hear.
